sprint 9
TY95MC/java-filmorate pull request #4
Opened 2023-08-10 13:57 UTC by TY95MC

2023-08-11 00:02 UTC, AnastasiyaFomkina requested changes

2023-08-11 00:02 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmValidationException.java
> +public class FilmValidationException extends RuntimeException {
Можно оставить один тип ошибки для всех ошибок валидации `ValidationException`, все остальное удалить

2023-08-11 00:02 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmValidationException.java
> +    public FilmValidationException(String message, Throwable cause) {
От неиспользуемых конструкторов точно нужно избавиться

2023-08-11 00:02 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@lombok.Data
```suggestion
@Data
```

2023-08-11 00:02 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@lombok.Data
```suggestion
@Data
```

2023-08-11 00:02 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
👍

2023-08-11 10:04 UTC, TY95MC commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                && film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28))
Исправил все, кроме этого. По ТЗ нужна валидация и именно ее мы тестируем. Если все проверки доверить спрингу, то нам и валидировать нечего будет. Но я почитаю про кастомную валидацию и попробую ее реализовать , спасибо!

2023-08-11 16:58 UTC, AnastasiyaFomkina requested changes

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public Collection<User> getUsers() {
Тоже лучше на List заменить

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                && film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28))
Так мы просто делегируем валидацию спрингу, мы избавляемся от ручной работы в пользу автоматизации процесса валидации. Сейчас мы делаем двойную работу, у нас есть как спринговая так и ручная валидация. Предлагаю удалить все аннотации валидации, и оставить ручную проверку тогда

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Нужно сразу добавить данное условие в конструктор User

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                && !user.getLogin().isBlank()
Уже проверяем в модели, эту проверку нужно удалить

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                && !user.getLogin().isBlank()
Нужно удалить либо проверку либо аннотацию

2023-08-11 16:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                && film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28))
Чтобы глубже разобраться в спинговой валидации стоит прочитать [вот эту статью](https://reflectoring.io/bean-validation-with-spring-boot/)

2023-08-11 16:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                && film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28))
Советую разобраться с тем как работает спринговая валидация прямо сейчас, дальше времени на нее не будет, а использоваться она будет очень часто.

2023-08-12 20:05 UTC, AnastasiyaFomkina approved these changes
Получилось очень клево, молодец 🔥

2023-08-24 14:39 UTC, merged